# Site settings
title: Osculating Plane
email: osculatingplane@ulfhedinn.net
description: > # this means to ignore newlines until "baseurl:"
  A blog about things fermented, by people mathematical.
baseurl: ""
url: http://osculatingplane.com
twitter_username: jontomas
github_username:  jontg

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Build settings
markdown: kramdown
